model:
  input_size: 7781
  d_model: 128
  nhead: 4
  num_encoder_layers: 1
  num_decoder_layers: 1
  dim_feedforward: 512
  dropout: 0.1

training:
  lr: 1.0e-5
  batch_size: 64
  epochs: 200
  patience: 30
  weight_decay: 5.0e-3
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_factor: 0.1
  lr_scheduler_patience: 10

data:
  path: /home/ckb2084/research/specpt-hst-sim/data/training_format/grism_training_sim_v3_regrid.parquet
  pretrained_autoencoder: ""
  val_split: 0.15
  test_split: 0.15
  split_by_group: true
  group_column: TARGETID

wandb:
  entity: ckb2084-rochester-institute-of-technology
  project: specpt-autoencoder-sim
