model:
  input_size: 7781
  d_model: 512
  nhead: 8
  num_encoder_layers: 3
  num_decoder_layers: 3
  dim_feedforward: 2048
  dropout: 0.1
  num_mlp_blocks: 12
  mlp_dim: 1024
  dropout_rate: 0.1

training:
  lr: 1.0e-4
  batch_size: 128
  epochs: 400
  patience: 50
  weight_decay: 5e-5
  lr_scheduler: ReduceLROnPlateau
  lr_scheduler_factor: 0.1
  lr_scheduler_patience: 20

data:
  path: /home/ckb2084/research/specpt-hst-sim/data/training_format/grism_training_sim_v1.pkl
  pretrained_autoencoder: /home/ckb2084/research/galax_spec/pretrained_weights/SpecPT_DESI_combined_autoencoder_150_new.pth
  pretrained_redshift: ""
  normalization: median
  val_split: 0.1
  test_split: 0.1

wandb:
  entity: ckb2084-rochester-institute-of-technology
  project: specpt-hst-sim-z

expected_duration_hours: 6
